image: "python:3"

before_script:
  - curl -sSL https://install.python-poetry.org | POETRY_HOME=$PWD/.poetry python -
  - export PATH=$PWD/.poetry/bin:$PATH
  - poetry config --local cache-dir "$PWD/.poetry/cache"
  - poetry config --local virtualenvs.in-project true
  - poetry install

stages:
  - Static Analysis
  - Test


lint:
  stage: Static Analysis
  allow_failure: true
  needs: []
  script:
    - poetry run flake8


# Run pytest tests in Python 3.8
test-py3.8:
  image: "python:3.8"
  stage: Test
  needs: []
  script:
    - poetry run pytest


# Run pytest tests in Python 3.9
test-py3.9:
  image: "python:3.9"
  stage: Test
  needs: []
  script:
    - poetry run pytest


# Run pytest tests in Python 3.10
test-py3.10:
  image: "python:3.10"
  stage: Test
  needs: []
  script:
    - poetry run pytest


# Run pytest tests in Python 3.11
test-py3.11:
  image: "python:3.11"
  stage: Test
  needs: []
  script:
    - poetry run pytest --cov
  artifacts:
    reports:
      junit: .xunit/tests.xml
